version: "3.8"
services: 
  rehber-postgresql-db:
    container_name: Rehber_Postgres_DB
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - rehber-postgresql-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=P@ssword
    networks: 
      - rehber-network 
  rapor-mssql-db:
    container_name: Rapor_MsSql_DB
    image: microsoft/mssql-server-linux:2017-CU13
    restart: always
    volumes: 
      - rapor-mssql-db:/var/opt/mssql/data
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword
    ports: 
      - "1434:1433"
    networks: 
      - rapor-network 
  rehber-rabbitmq:
    container_name: Rehber_RabbitMq
    image: rabbitmq:3.8.9-management
    restart: always
    hostname: rehberrabbitmq
    volumes:
      - rehber-rabbitmq:/var/lib/rabbitmq
    environment: 
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=P@ssword
    ports:
      - 15673:15672
      - 5673:5672
    networks: 
      - rapor-network 
  rehber-api:
    container_name: Rehber_Api
    build: ./Services/Rehber/RiseTechnologyAssessment.Services.Rehber.API
    restart: always
    environment: 
     - ASPNETCORE_ENVIRONMENT=Production
     - ConnectionStrings=User ID=user;Password=P@ssword;Server=rehber-postgresql-db;Port=5433;Database=DevelopmentRehber;Integrated Security=true;Pooling=true;
    ports:
      - 5010:4500
    networks: 
      - rehber-network
    depends_on:
     - rehber-postgresql-db
  rapor-api:
    container_name: Rapor_Api
    build: ./Services/Rapor/RiseTechnologyAssessment.Services.Rapor.API
    restart: always
    environment: 
     - ASPNETCORE_ENVIRONMENT=Production
     - ConnectionStrings=Server=rapor-mssql-db;Database=DevelopmentRapor;User ID=sa;Password=P@ssword
     - RabbitMQ_HostName=rehber-rabbitmq
     - RabbitMQ_VirtualHost=/
     - RabbitMQ_UserName=user
     - RabbitMQ_Password=P@ssword
    ports:
      - 5011:4500
    networks: 
      - rapor-network
    depends_on:
     - rapor-mssql-db
     - rehber-rabbitmq
volumes: 
  rehber-postgresql-db:
  rapor-mssql-db:
  rehber-rabbitmq:
networks: 
  rehber-network:
    driver: bridge
  rapor-network:
    driver: bridge